{% set name = "pyCroscopy" %}
{% set version = "0.60.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: fb49d366d74954a4027a14e05589c60e50fc18af5f69d278e9bd6720ecc9bb78

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python
    - pip
    - pytest-runner
  run:
    - python
    - numpy_groupies ==0.9.7
    - h5py >=2.6.0
    - igor
    - matplotlib >=2.0.0
    - scikit-learn >=0.17.1
    - xlrd >=1.0.0
    - joblib >=0.11.0
    - psutil
    - scikit-image >=0.12.3
    - scipy >=0.17.1
    - numpy >=1.13.0
    - ipywidgets >=5.2.2
    - ipython >=5.1.0,<6  # [py2k]  # IPython 6.0+ does not support Python 2.6, 2.7, 3.0, 3.1, or 3.2
    - ipython >=6  # [py3k]  # Beginning with IPython 6.0, Python 3.3 and above is required.
    - six
    - pyusid ==0.0.5.1
    - gwyfile
    - unittest2  # [py27]

test:
  imports:
    - pycroscopy

about:
  home: https://github.com/pycroscopy/pycroscopy
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Utilities for scientific analysis of nanoscale imaging data'
  description: |
    pycroscopy is a python package for image processing and scientific analysis
    of imaging modalities such as multi-frequency scanning probe microscopy,
    scanning tunneling spectroscopy, x-ray diffraction microscopy, and transmission
    electron microscopy. pycroscopy uses a data-centric model wherein the raw data
    collected from the microscope, results from analysis and processing routines
    are all written to standardized hierarchical data format (HDF5) files for
    traceability, reproducibility, and provenance.
  doc_url: https://pycroscopy.github.io/pycroscopy/index.html
  dev_url: https://github.com/pycroscopy/pycroscopy

extra:
  recipe-maintainers:
    - carlodri
    - ssomnath
    - compphyschris
