# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.5
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "S0X6C4o+MonUB/xXmwtrFN+4g0ZHnD5lKJhB3uzEtbOLsF3AW/PimTybiL45ShkOjRCrSWG0u+ZzcVmvYA48zTmq+hWbAjVjBbMydc5ivDAdglCTkvA8ExY9ChiQn+7Nh1LXkyamiB7c9M+IuEiunBVV4M5yNUb6xOAuQkAQ7YrX2l/cuSVx8Srla2HI4sChmVCvqs4eWq2J/ci1x2nsAlHuNnsmpLD5VsI6XZyyofMwmZHV854P0ElfdVWQWnuUhWltbaTLNMp/U0WQDPp5iQCVLCfE7sYoL/TDNef9FLVyZAHZsD7mN5JJ7zG7hDFZm0CJlx6/N0g+GCAo5xjSRCScpJeViPZUHLW+b/LF8hjyg/M3dFTkoWvdUBdBTGSgfbuej/+F1OMD2kNtES5PmDIchqej1ZBPYve/jLAb7bekqD4QNwDMcy90mARgqwz78l0EJpR4peskS2Fmg0aX9CRMeM8EudxrrXK0o+Q3oQgu5ndzDmADwDzWXTGWd5vn0/zmNUZ/eo2JaaCpCU00rFS0nTdkgmEOo17z7lmkC1KPHDcCb9PxDTMMUGQhFe9WoODQZpeCldsAlSXqWdrYpiwq/ZsJSFTfVY0w0BG2vbtHpr3kcUVP9TohNwyJpjjm9+E3DRnR60eNpQ+a1pjEgDT1jb95BNRgkFnItIL9Aec="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
